apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: teleiostejiriacr.azurecr.io/payment-service:v1.0
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: payment-secret
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /api/payments/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/payments/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20

