apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  database-url: cG9zdGdyZXNxbCthc3luY3BnOi8vcG9zdGdyZXM6cGFzc3dvcmRAbG9jYWxob3N0OjU0MzIvcmlkZXNoYXJlX3BheW1lbnRz
  jwt-secret: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
