apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: rideshare
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
